### DISCUSSION TITLE
Great Tool -is dnssniffer + Dns Filter How to get this work?

### DISCUSSION THREAD

**Discussion by ToniToga** [dmachard/DNS-collector#109] [Q&A] [answered]
The go-dns-collector is a great tool, exactly what i looked for. But I have one Problem.
I cannot get the DNS-Filter get to work. Perhabs because I'm using the dnssniffer to get the DNS-Logs.
Am I right?
My Goal is to filter some Domain names, which shouldn't get logged.

My config looks like:

```
global:
  trace:
    verbose: true

multiplexer:
  collectors:
    - name: dnssniff
      dns-sniffer:
        port: 53
        device: eth0
        capture-dns-queries: true
        capture-dns-replies: true
        cache-support: true
        query-timeout: 5.0

  transforms:
    filtering:
      drop-domain-file: "/etc/dnscollector/exceptions"
      drop-fqdn-file: "/etc/dnscollector/exceptions2"
      log-queries: true
      log-replies: true

  loggers:
    - name: loki
      lokiclient:
        server-url: "http://XYZ.Intern.de:3100/loki/api/v1/push"
        job-name: "dnscollector"
        text-format: "localtime identity qr queryip family protocol qname qtype rcode"

  routes:
    - from: [dnssniff]
      to: [loki]
```

**Comment by dmachard** [comment]
Hi,

If working fine with the following config in my side.
Can you retry by redirecting to the console in first ? 

```
multiplexer:
  collectors:
    - name: sniff
      dns-sniffer:
        port: 53
        device: wlp2s0
        capture-dns-queries: true
        capture-dns-replies: true
        cache-support: true
        query-timeout: 5.0
      transforms:
        filtering:
          drop-fqdn-file: "./testsdata/filtering_fqdn.txt"
          log-queries: false
          log-replies: true

  loggers:
    - name: console
      stdout:
        mode: text

  routes:
    - from: [ sniff ]
      to: [ console ]
```
