### DISCUSSION TITLE
can we read the raw dnstap file and generate JSON output or YAML all when records are added to DNSTAP file in realtime?

### DISCUSSION THREAD

**Discussion by wonderbee77** [dmachard/DNS-collector#1226] [General]
can we read the raw dnstap file and generate JSON output or YAML all when records are added to DNSTAP file in realtime?

i need to get the same output as i get from "dnstap-read -y /etc/bind/test.dnstap" command. But with file tailing functionality. Do we have that capability yet? Output in YAML or JSON

````
root@unbound-ansible-deployment-2:~# dnstap-read -y /etc/bind/test.dnstap
type: MESSAGE
identity: dns-bind
version: bind
message:
  type: RESOLVER_QUERY
  query_time: !!timestamp 2023-02-20T01:19:12Z
  message_size: 40b
  socket_family: INET
  socket_protocol: UDP
  query_address: 155.138.134.112
  response_address: 1.1.1.1
  query_port: 57650
  response_port: 53
  query_message_data:
    opcode: QUERY
    status: NOERROR
    id:  65208
    flags: rd cd
    QUESTION: 1
    ANSWER: 0
    AUTHORITY: 0
    ADDITIONAL: 1
    OPT_PSEUDOSECTION:
      EDNS:
        version: 0
        flags: do
        udp: 512
        COOKIE: 8f69fcf7994424a1
    QUESTION_SECTION:
      - . IN DNSKEY
  query_message: |
    ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id:  65208
    ;; flags: rd cd    ; QUESTION: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
    ;; OPT PSEUDOSECTION:
    ; EDNS: version: 0, flags: do; udp: 512
    ; COOKIE: 8f69fcf7994424a1
    ;; QUESTION SECTION:
    ;.				IN	DNSKEY
    
---
```
