### DISCUSSION TITLE
matching with arrays

### DISCUSSION THREAD

**Discussion by drenton1** [dmachard/DNS-collector#795] [Q&A] [answered]
I'm looking to filter dnstap messages where the response ip address is 0.0.0.0.  Consider the below dnstap json.  How would I create a pipeline with dnsmessage > matching > include to filter for the 0.0.0.0 ip.  I tried the following without success.

```
pipelines:
  - name: filter-messages
    dnsmessage:
      matching:
        include:
          dns.resource-records.an.0.rdata: "0.0.0.0"
```

```
{
  "dns": {
    "resource-records": {
      "an": [
        {
          "name": "test.example.com",
          "rdatatype": "A",
          "class": "IN",
          "ttl": 86400,
          "rdata": "0.0.0.0"
        }
      ],
      "ns": [],
      "ar": []
    }
  }
}
```

Thanks
