### ISSUE TITLE
Include subnet information for: dnscollector_requesters_top_total

### ISSUE THREAD

**Issue by KVInventoR** [dmachard/DNS-collector#26]
It's also will be useful to have some additional statistics to analyze number queries from similar subnets.
Example:

```
dnscollector_requesters_top_total{stream="beta-vm01",ip="172.253.206.36"} 38 
dnscollector_requesters_top_total{stream="beta-vm01",ip="178.20.157.236"} 35
dnscollector_requesters_top_total{stream="beta-vm01",ip="172.253.255.35"} 34
dnscollector_requesters_top_total{stream="beta-vm01",ip="178.20.156.245"} 33
dnscollector_requesters_top_total{stream="beta-vm01",ip="148.66.138.87"} 33
dnscollector_requesters_top_total{stream="beta-vm01",ip="114.119.176.141"} 31
dnscollector_requesters_top_total{stream="beta-vm01",ip="165.227.94.23"} 31
dnscollector_requesters_top_total{stream="beta-vm01",ip="172.253.1.133"} 30
dnscollector_requesters_top_total{stream="beta-vm01",ip="172.253.255.37"} 30
dnscollector_requesters_top_total{stream="beta-vm01",ip="172.253.1.132"} 30
dnscollector_requesters_top_total{stream="beta-vm01",ip="172.253.255.33"} 26
dnscollector_requesters_top_total{stream="beta-vm01",ip="172.253.206.33"} 26
dnscollector_requesters_top_total{stream="beta-vm01",ip="172.253.206.37"} 25
```

I am pretty sure:
172.253.206.36, 172.253.206.33, 172.253.206.37 it's same subnet range 

If geoip module for AS information enabled, is it possible to add additional label, like as: subnet_range 
after that, I will be able over grafana calculate number of queries from same subnet range.

probably, same feature can be useful for another metrics.

what is the goal?
I just would like to have some system, which will give possibility to recognize attack to our DNS infrastructure.

**Comment by dmachard** [comment]
@KVInventoR 
Before to add more features, I need to have  some feedback regarding performance (cpu and memory). 
I don't want to decrease the performance of the collector.

**Comment by KVInventoR** [comment]
Hi @dmachard 
of course, I can try to connect another out dns servers to push dnstap messages and check performance
but everything, which related to geoip can break performance

and it's the best to split one big application to small different applications which can scale

**Comment by KVInventoR** [comment]
also, 
probably you saw, but I found it's really useful:
https://www.youtube.com/watch?v=M8nYWBpbwWg

**Comment by dmachard** [comment]
Thank to share the video, i will try that :) 
By the way, I created a discussion about Loki+Grafana for DNS logging here: https://github.com/dmachard/dns-collector/discussions/27.
if you want we can share our progress

**Comment by johnhtodd** [comment]
This could be an arbitrary configurable subnet mask as an easy solution.  At a minimum, the global BGP table space typically only recognizes /24 and /48 as the "smallest" networks, so that usually aggregates /32 and /128 addresses into much more manage-able sizes, and makes stats more meaningful.

**Comment by dmachard** [comment]
Hi @KVInventoR,

This can be achieved natively using the `userprivacy` transformer combined with a dedicated Prometheus pipeline.

By applying subnet masking (e.g. `/24` for IPv4 and `/48` for IPv6) in a transform before the Prometheus logger, individual IP host bits are zeroed out, and `dnscollector_top_requesters` aggregates counts directly per subnet range:

```yaml
pipelines:
  - name: ingress-dnstap
    dnstap:
      listen-ip: 0.0.0.0
      listen-port: 6000
    routing-policy:
      forward: [ subnet-aggregation ]

  - name: subnet-aggregation
    transforms:
      user-privacy:
        anonymize-ip: true
        anonymize-ipv4-bits: "24"
        anonymize-ipv6-bits: "::/48"
    routing-policy:
      forward: [ prom-subnets ]

  - name: prom-subnets
    prometheus:
      listen-ip: 0.0.0.0
      listen-port: 8081
      prometheus-prefix: "dnscollector_subnets"
```

In Prometheus, dnscollector_subnets_top_requesters will report aggregated metrics by subnet (ip="172.253.206.0").

Closing this issue!
