### ISSUE TITLE
kafka_auto-reconnect_failure

### ISSUE THREAD

**Issue by bondar-aleksandr** [dmachard/DNS-collector#973]
**Describe the bug**
dnscollector fails to reconnect to kafka after kafka restart. environment - k8s. 
dnscollector kafka config:
```
    kafkaproducer:
      remote-address: kafka.kafka.svc.cluster.local
      remote-port: 9092
      connect-timeout: 30
      retry-interval: 20
      sasl-support: true
      sasl-mechanism: "SCRAM-SHA-512"
      sasl-username: "XXX"
      sasl-password: "XXX"
      topic: "dnstap_logs"
      mode: json
      partition: null
      buffer-size: 250
      chan-buffer-size: 512000
      flush-interval: 1
      compression: lz4
```
If we recreate the dnscollector POD, it connects to kafka just fine.

**To Reproduce**
scale kafka to 0 replicas and rescale back to 3 while dnscollecor pod is running 

**Expected behavior**
successfull reconnect upon connectivity restoration

**Additional context**
- dnscollector version - 1.5.0  
- k8s version 1.30.11
- kafka version 4
- dnscollector logs attached

![Image](https://github.com/user-attachments/assets/668c31c9-ee2f-4bdc-85ad-95fabd4a7e28)
